version: '3.8'

services:
  zerepy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zerepy-server
    ports:
      - "8000:8000"
    volumes:
      - ./agents:/app/agents
      - ./.env:/app/.env
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s 